import { LessonHistory } from '@/types/userLessonHistory';

export const LESSON_HISTORY_MOCK: LessonHistory[] = [
  {
    id: '1',
    status: '결제 성공',
    time: '3월 17일 19시 01분',
    content: 'PT를 했다 PT 끝났다',
    seller: '이희수',
    price: 500000,
  },
  {
    id: '2',
    status: '결제 취소',
    time: '3월 17일 19시 02분',
    content: 'PT를 했다 PT 끝났다',
    seller: '이희수',
    price: 400000,
  },
  {
    id: '3',
    status: '결제 환불',
    time: '3월 19일 19시 05분',
    content: 'PT를 했다 PT 끝났다 다이어트는 오늘부터 시작이야',
    seller: '이희수',
    price: 800000,
  },
  {
    id: '4',
    status: '결제 환불',
    time: '3월 19일 19시 05분',
    content: 'PT를 했다 PT 끝났다 오늘은 너무 힘들다',
    seller: '이희수',
    price: 400000,
  },
  {
    id: '5',
    status: '결제 환불',
    time: '3월 19일 19시 05분',
    content: 'PT를 했다 PT 끝났다 다이어트는 내일부터 시작해야지',
    seller: '이희수',
    price: 400000,
  },
  {
    id: '6',
    status: '결제 환불',
    time: '3월 19일 19시 05분',
    content: 'PT를 했다 PT 끝났다 집에가고싶따~',
    seller: '이희수',
    price: 100000,
  },
  {
    id: '7',
    status: '결제 환불',
    time: '3월 19일 19시 05분',
    content: 'PT를 했다 PT 끝났다 잘지내니',
    seller: '성도형',
    price: 200000,
  },
  {
    id: '8',
    status: '결제 환불',
    time: '3월 19일 19시 05분',
    content: 'PT를 했다 PT 끝났다 집에가고싶당',
    seller: '박수관',
    price: 300000,
  },
  {
    id: '9',
    status: '결제 환불',
    time: '3월 19일 19시 05분',
    content: 'PT를 했다 PT 끝났다',
    seller: '이희수',
    price: 400000,
  },
  {
    id: '10',
    status: '결제 환불',
    time: '3월 19일 19시 05분',
    content: 'PT를 했다 PT 끝났다',
    seller: '이희수',
    price: 400000,
  },
  {
    id: '11',
    status: '결제 환불',
    time: '3월 19일 19시 05분',
    content: 'PT를 했다 PT 끝났다',
    seller: '이희수',
    price: 400000,
  },
];
